name: Deploy to EC2

on:
    push:
        branches:
            -   main

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: stage

        steps:
            -   name: Set lowercase actor
                id: vars
                run: echo "actor_lowercase=$(echo '${{github.actor}}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

            -   name: Set up SSH
                uses: webfactory/ssh-agent@v0.9.0
                with:
                    ssh-private-key: ${{ secrets.EC2_DEPLOY_KEY }}

            -   name: Test SSH Connection
                run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} "echo 'SSH connection successful'"
                
            -   name: Deploy to EC2
                run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} 'bash /home/ubuntu/app/deploy.sh'
