name: Build and Push Docker image

on:
    push:
        branches:
            -   main

jobs:
    build:
        runs-on: ubuntu-latest
        environment: stage

        permissions:
            contents: read
            packages: write

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Set lowercase actor
                id: vars
                run: echo "actor_lower=$(echo '${{ github.actor }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
            
            -   name: Log in to GHCR
                uses: docker/login-action@v3
                with: 
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GHCR_TOKEN }}

            -   name: Build and Push Docker image
                uses: docker/build-push-action@v5
                with:
                    context: .
                    push: true
                    tags: ghcr.io/${{ steps.vars.outputs.actor_lower }}/learn-async-go-app:latest
